services:
  - type: web
    name: openmeteo-api
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: POETRY_NO_INTERACTION
        value: 1
